export function validTestEnvironment(
  overrides: Record<string, string> = {},
): Record<string, string> {
  return {
    SWAR_ENV: 'test',
    BACKEND_HOST: '127.0.0.1',
    BACKEND_PORT: '3000',
    PUBLIC_API_URL: 'http://127.0.0.1:3000/api/v1',
    SECURITY_WS_URL: 'ws://127.0.0.1:3000/ws/security',
    CORS_ALLOWED_ORIGINS: 'http://127.0.0.1:5173',
    HTTP_BODY_LIMIT_BYTES: '1024',
    HTTP_REQUEST_TIMEOUT_MS: '30000',
    SHUTDOWN_TIMEOUT_MS: '5000',
    API_RATE_LIMIT_WINDOW_SECONDS: '60',
    API_SENSITIVE_RATE_LIMIT_MAX: '10',
    API_MUTATION_RATE_LIMIT_MAX: '60',
    API_QUERY_RATE_LIMIT_MAX: '300',
    SECURITY_WS_REPLAY_MAX_EVENTS: '100',
    SECURITY_WS_SUBSCRIPTION_MAX_CALLS: '50',
    SECURITY_WS_INBOUND_RATE_LIMIT_MAX: '60',
    ENROLLMENT_MAX_SAMPLES: '5',
    ENROLLMENT_MAX_SAMPLE_BYTES: '1048576',
    ENROLLMENT_MAX_TOTAL_BYTES: '5242880',
    ENROLLMENT_MAX_DECLARED_DURATION_MS: '30000',
    STEP_UP_CHALLENGE_TTL_SECONDS: '300',
    DATABASE_URL: 'postgresql://swar_test:test-only-password@127.0.0.1:5432/swar_test',
    POSTGRES_POOL_MAX: '5',
    POSTGRES_IDLE_TIMEOUT_MS: '10000',
    POSTGRES_CONNECTION_TIMEOUT_MS: '5000',
    ML_INTERNAL_URL: 'http://127.0.0.1:8000',
    ML_EVIDENCE_MODE: 'SHADOW',
    ML_CONTROL_MAX_ATTEMPTS: '2',
    ML_CONTROL_RETRY_BACKOFF_MS: '10',
    INTERNAL_AUTH_CLOCK_SKEW_SECONDS: '30',
    ML_INTERNAL_SECRET: 'ml-internal-secret-for-tests-only-123456',
    VERIFICATION_CALLBACK_SECRET: 'verification-callback-secret-tests-123456',
    LIVEKIT_URL: 'ws://127.0.0.1:7880',
    LIVEKIT_API_KEY: 'test-livekit-key',
    LIVEKIT_API_SECRET: 'livekit-api-secret-for-tests-only-123456',
    LIVEKIT_PARTICIPANT_GRANT_TTL_SECONDS: '300',
    ANALYSIS_SESSION_TTL_SECONDS: '900',
    DOWNSTREAM_HTTP_TIMEOUT_MS: '500',
    DOWNSTREAM_WEBSOCKET_TIMEOUT_MS: '500',
    JWT_ACCESS_SECRET: 'access-secret-for-tests-only-1234567890',
    JWT_REFRESH_SECRET: 'refresh-secret-for-tests-only-0987654321',
    JWT_ISSUER: 'swar-test',
    JWT_AUDIENCE: 'swar-test-api',
    JWT_ACCESS_TTL_SECONDS: '300',
    JWT_CLOCK_TOLERANCE_SECONDS: '0',
    REFRESH_SESSION_TTL_SECONDS: '3600',
    AUTH_LOGIN_MAX_ATTEMPTS: '5',
    AUTH_LOGIN_WINDOW_SECONDS: '300',
    IDEMPOTENCY_TTL_SECONDS: '3600',
    IDEMPOTENCY_MAX_ENTRIES: '1000',
    VOICEPRINT_ENCRYPTION_KEY: Buffer.alloc(32, 7).toString('base64'),
    VOICEPRINT_ENCRYPTION_KEY_VERSION: 'test-key-v1',
    ...overrides,
  };
}

export function setValidTestEnvironment(overrides: Record<string, string> = {}): void {
  Object.assign(process.env, validTestEnvironment(overrides));
}
